language: python
cache:
  apt: true
python:
  - "2.7"
before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq bats
  - git clone git://github.com/yyuu/pyenv.git $HOME/.pyenv
before_script:
  - echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bash_pyenv
  - echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bash_pyenv
script:
  - . ~/.bash_pyenv && ./run-tests.sh --tap
