language: python
cache:
  apt: true
python:
  - "2.7"
before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq bats
script:
  - ./run-tests.sh --tap
